server:
  port: 9668

spring:
  application:
    name: credit-server
  profiles:
    active: local

eureka:
  instance:
    hostname: 192.168.1.15
  client:
    service-url:
      defaultZone: http://192.168.1.15:9888/eureka/