server:
  port: 9448

spring:
  application:
    name: order-server
  profiles:
    active: local

eureka:
  instance:
    hostname: 192.168.1.15
  client:
    service-url:
      defaultZone: http://192.168.1.15:9888/eureka/
    registry-fetch-interval-seconds: 5

