server:
  port: 9889

spring:
  application:
    name: zuul-getway
  profiles:
    active: local

eureka:
  instance:
    hostname: 192.168.1.15
  client:
    service-url:
      defaultZone: http://192.168.1.15:9888/eureka/

zuul:
  retryable: true
  routes:
    order-service:
      path: /order/**