server:
  port: 9889

spring:
  application:
    name: zuul-getway
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://192.168.1.15:3306/study0?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: liberty123
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  instance:
    hostname: 192.168.1.15
  client:
    service-url:
      defaultZone: http://192.168.1.15:9888/eureka/

zuul:
  retryable: true
  routes:
    order-server:
      path: /order/**